package com.init.mini.web.entity;

import com.init.mini.web.dto.BasePO;

import java.math.BigDecimal;
import java.util.Date;

public class Goods extends BasePO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.target_type
     *
     * @mbg.generated
     */
    private String targetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.year
     *
     * @mbg.generated
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.month
     *
     * @mbg.generated
     */
    private String month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.work_age
     *
     * @mbg.generated
     */
    private Integer workAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.plan_name
     *
     * @mbg.generated
     */
    private String planName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.target_value
     *
     * @mbg.generated
     */
    private BigDecimal targetValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.dept_code
     *
     * @mbg.generated
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.dept_level
     *
     * @mbg.generated
     */
    private String deptLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.updated_date
     *
     * @mbg.generated
     */
    private Date updatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.created_date
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.target_type
     *
     * @return the value of goods.target_type
     *
     * @mbg.generated
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.target_type
     *
     * @param targetType the value for goods.target_type
     *
     * @mbg.generated
     */
    public void setTargetType(String targetType) {
        this.targetType = targetType == null ? null : targetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.year
     *
     * @return the value of goods.year
     *
     * @mbg.generated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.year
     *
     * @param year the value for goods.year
     *
     * @mbg.generated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.month
     *
     * @return the value of goods.month
     *
     * @mbg.generated
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.month
     *
     * @param month the value for goods.month
     *
     * @mbg.generated
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.work_age
     *
     * @return the value of goods.work_age
     *
     * @mbg.generated
     */
    public Integer getWorkAge() {
        return workAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.work_age
     *
     * @param workAge the value for goods.work_age
     *
     * @mbg.generated
     */
    public void setWorkAge(Integer workAge) {
        this.workAge = workAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.plan_name
     *
     * @return the value of goods.plan_name
     *
     * @mbg.generated
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.plan_name
     *
     * @param planName the value for goods.plan_name
     *
     * @mbg.generated
     */
    public void setPlanName(String planName) {
        this.planName = planName == null ? null : planName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.target_value
     *
     * @return the value of goods.target_value
     *
     * @mbg.generated
     */
    public BigDecimal getTargetValue() {
        return targetValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.target_value
     *
     * @param targetValue the value for goods.target_value
     *
     * @mbg.generated
     */
    public void setTargetValue(BigDecimal targetValue) {
        this.targetValue = targetValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.dept_code
     *
     * @return the value of goods.dept_code
     *
     * @mbg.generated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.dept_code
     *
     * @param deptCode the value for goods.dept_code
     *
     * @mbg.generated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.dept_level
     *
     * @return the value of goods.dept_level
     *
     * @mbg.generated
     */
    public String getDeptLevel() {
        return deptLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.dept_level
     *
     * @param deptLevel the value for goods.dept_level
     *
     * @mbg.generated
     */
    public void setDeptLevel(String deptLevel) {
        this.deptLevel = deptLevel == null ? null : deptLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.updated_by
     *
     * @return the value of goods.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.updated_by
     *
     * @param updatedBy the value for goods.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.updated_date
     *
     * @return the value of goods.updated_date
     *
     * @mbg.generated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.updated_date
     *
     * @param updatedDate the value for goods.updated_date
     *
     * @mbg.generated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.created_by
     *
     * @return the value of goods.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.created_by
     *
     * @param createdBy the value for goods.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.created_date
     *
     * @return the value of goods.created_date
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.created_date
     *
     * @param createdDate the value for goods.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}