package com.init.mini.web.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;

@ApiModel(value = "管理员 model")
public class JsSysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.user_code
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "用户userCode", required = true, example = "#001")
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.login_code
     *
     * @mbg.generated
     */
    private String loginCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.sign
     *
     * @mbg.generated
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.wx_openid
     *
     * @mbg.generated
     */
    private String wxOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.mobile_imei
     *
     * @mbg.generated
     */
    private String mobileImei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.user_type
     *
     * @mbg.generated
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.ref_code
     *
     * @mbg.generated
     */
    private String refCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.ref_name
     *
     * @mbg.generated
     */
    private String refName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.mgr_type
     *
     * @mbg.generated
     */
    private String mgrType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.pwd_security_level
     *
     * @mbg.generated
     */
    private Short pwdSecurityLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.pwd_update_date
     *
     * @mbg.generated
     */
    private Date pwdUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.pwd_update_record
     *
     * @mbg.generated
     */
    private String pwdUpdateRecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.pwd_question
     *
     * @mbg.generated
     */
    private String pwdQuestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.pwd_question_answer
     *
     * @mbg.generated
     */
    private String pwdQuestionAnswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.pwd_question_2
     *
     * @mbg.generated
     */
    private String pwdQuestion2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.pwd_question_answer_2
     *
     * @mbg.generated
     */
    private String pwdQuestionAnswer2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.pwd_question_3
     *
     * @mbg.generated
     */
    private String pwdQuestion3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.pwd_question_answer_3
     *
     * @mbg.generated
     */
    private String pwdQuestionAnswer3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.pwd_quest_update_date
     *
     * @mbg.generated
     */
    private Date pwdQuestUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.last_login_ip
     *
     * @mbg.generated
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.last_login_date
     *
     * @mbg.generated
     */
    private Date lastLoginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.freeze_date
     *
     * @mbg.generated
     */
    private Date freezeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.freeze_cause
     *
     * @mbg.generated
     */
    private String freezeCause;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.user_weight
     *
     * @mbg.generated
     */
    private Integer userWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.corp_code
     *
     * @mbg.generated
     */
    private String corpCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.corp_name
     *
     * @mbg.generated
     */
    private String corpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_s1
     *
     * @mbg.generated
     */
    private String extendS1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_s2
     *
     * @mbg.generated
     */
    private String extendS2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_s3
     *
     * @mbg.generated
     */
    private String extendS3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_s4
     *
     * @mbg.generated
     */
    private String extendS4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_s5
     *
     * @mbg.generated
     */
    private String extendS5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_s6
     *
     * @mbg.generated
     */
    private String extendS6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_s7
     *
     * @mbg.generated
     */
    private String extendS7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_s8
     *
     * @mbg.generated
     */
    private String extendS8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_i1
     *
     * @mbg.generated
     */
    private BigDecimal extendI1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_i2
     *
     * @mbg.generated
     */
    private BigDecimal extendI2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_i3
     *
     * @mbg.generated
     */
    private BigDecimal extendI3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_i4
     *
     * @mbg.generated
     */
    private BigDecimal extendI4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_f1
     *
     * @mbg.generated
     */
    private BigDecimal extendF1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_f2
     *
     * @mbg.generated
     */
    private BigDecimal extendF2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_f3
     *
     * @mbg.generated
     */
    private BigDecimal extendF3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_f4
     *
     * @mbg.generated
     */
    private BigDecimal extendF4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_d1
     *
     * @mbg.generated
     */
    private Date extendD1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_d2
     *
     * @mbg.generated
     */
    private Date extendD2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_d3
     *
     * @mbg.generated
     */
    private Date extendD3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_sys_user.extend_d4
     *
     * @mbg.generated
     */
    private Date extendD4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.user_code
     *
     * @return the value of js_sys_user.user_code
     *
     * @mbg.generated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.user_code
     *
     * @param userCode the value for js_sys_user.user_code
     *
     * @mbg.generated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.login_code
     *
     * @return the value of js_sys_user.login_code
     *
     * @mbg.generated
     */
    public String getLoginCode() {
        return loginCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.login_code
     *
     * @param loginCode the value for js_sys_user.login_code
     *
     * @mbg.generated
     */
    public void setLoginCode(String loginCode) {
        this.loginCode = loginCode == null ? null : loginCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.user_name
     *
     * @return the value of js_sys_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.user_name
     *
     * @param userName the value for js_sys_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.password
     *
     * @return the value of js_sys_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.password
     *
     * @param password the value for js_sys_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.email
     *
     * @return the value of js_sys_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.email
     *
     * @param email the value for js_sys_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.mobile
     *
     * @return the value of js_sys_user.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.mobile
     *
     * @param mobile the value for js_sys_user.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.phone
     *
     * @return the value of js_sys_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.phone
     *
     * @param phone the value for js_sys_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.sex
     *
     * @return the value of js_sys_user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.sex
     *
     * @param sex the value for js_sys_user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.avatar
     *
     * @return the value of js_sys_user.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.avatar
     *
     * @param avatar the value for js_sys_user.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.sign
     *
     * @return the value of js_sys_user.sign
     *
     * @mbg.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.sign
     *
     * @param sign the value for js_sys_user.sign
     *
     * @mbg.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.wx_openid
     *
     * @return the value of js_sys_user.wx_openid
     *
     * @mbg.generated
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.wx_openid
     *
     * @param wxOpenid the value for js_sys_user.wx_openid
     *
     * @mbg.generated
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid == null ? null : wxOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.mobile_imei
     *
     * @return the value of js_sys_user.mobile_imei
     *
     * @mbg.generated
     */
    public String getMobileImei() {
        return mobileImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.mobile_imei
     *
     * @param mobileImei the value for js_sys_user.mobile_imei
     *
     * @mbg.generated
     */
    public void setMobileImei(String mobileImei) {
        this.mobileImei = mobileImei == null ? null : mobileImei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.user_type
     *
     * @return the value of js_sys_user.user_type
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.user_type
     *
     * @param userType the value for js_sys_user.user_type
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.ref_code
     *
     * @return the value of js_sys_user.ref_code
     *
     * @mbg.generated
     */
    public String getRefCode() {
        return refCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.ref_code
     *
     * @param refCode the value for js_sys_user.ref_code
     *
     * @mbg.generated
     */
    public void setRefCode(String refCode) {
        this.refCode = refCode == null ? null : refCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.ref_name
     *
     * @return the value of js_sys_user.ref_name
     *
     * @mbg.generated
     */
    public String getRefName() {
        return refName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.ref_name
     *
     * @param refName the value for js_sys_user.ref_name
     *
     * @mbg.generated
     */
    public void setRefName(String refName) {
        this.refName = refName == null ? null : refName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.mgr_type
     *
     * @return the value of js_sys_user.mgr_type
     *
     * @mbg.generated
     */
    public String getMgrType() {
        return mgrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.mgr_type
     *
     * @param mgrType the value for js_sys_user.mgr_type
     *
     * @mbg.generated
     */
    public void setMgrType(String mgrType) {
        this.mgrType = mgrType == null ? null : mgrType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.pwd_security_level
     *
     * @return the value of js_sys_user.pwd_security_level
     *
     * @mbg.generated
     */
    public Short getPwdSecurityLevel() {
        return pwdSecurityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.pwd_security_level
     *
     * @param pwdSecurityLevel the value for js_sys_user.pwd_security_level
     *
     * @mbg.generated
     */
    public void setPwdSecurityLevel(Short pwdSecurityLevel) {
        this.pwdSecurityLevel = pwdSecurityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.pwd_update_date
     *
     * @return the value of js_sys_user.pwd_update_date
     *
     * @mbg.generated
     */
    public Date getPwdUpdateDate() {
        return pwdUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.pwd_update_date
     *
     * @param pwdUpdateDate the value for js_sys_user.pwd_update_date
     *
     * @mbg.generated
     */
    public void setPwdUpdateDate(Date pwdUpdateDate) {
        this.pwdUpdateDate = pwdUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.pwd_update_record
     *
     * @return the value of js_sys_user.pwd_update_record
     *
     * @mbg.generated
     */
    public String getPwdUpdateRecord() {
        return pwdUpdateRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.pwd_update_record
     *
     * @param pwdUpdateRecord the value for js_sys_user.pwd_update_record
     *
     * @mbg.generated
     */
    public void setPwdUpdateRecord(String pwdUpdateRecord) {
        this.pwdUpdateRecord = pwdUpdateRecord == null ? null : pwdUpdateRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.pwd_question
     *
     * @return the value of js_sys_user.pwd_question
     *
     * @mbg.generated
     */
    public String getPwdQuestion() {
        return pwdQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.pwd_question
     *
     * @param pwdQuestion the value for js_sys_user.pwd_question
     *
     * @mbg.generated
     */
    public void setPwdQuestion(String pwdQuestion) {
        this.pwdQuestion = pwdQuestion == null ? null : pwdQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.pwd_question_answer
     *
     * @return the value of js_sys_user.pwd_question_answer
     *
     * @mbg.generated
     */
    public String getPwdQuestionAnswer() {
        return pwdQuestionAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.pwd_question_answer
     *
     * @param pwdQuestionAnswer the value for js_sys_user.pwd_question_answer
     *
     * @mbg.generated
     */
    public void setPwdQuestionAnswer(String pwdQuestionAnswer) {
        this.pwdQuestionAnswer = pwdQuestionAnswer == null ? null : pwdQuestionAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.pwd_question_2
     *
     * @return the value of js_sys_user.pwd_question_2
     *
     * @mbg.generated
     */
    public String getPwdQuestion2() {
        return pwdQuestion2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.pwd_question_2
     *
     * @param pwdQuestion2 the value for js_sys_user.pwd_question_2
     *
     * @mbg.generated
     */
    public void setPwdQuestion2(String pwdQuestion2) {
        this.pwdQuestion2 = pwdQuestion2 == null ? null : pwdQuestion2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.pwd_question_answer_2
     *
     * @return the value of js_sys_user.pwd_question_answer_2
     *
     * @mbg.generated
     */
    public String getPwdQuestionAnswer2() {
        return pwdQuestionAnswer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.pwd_question_answer_2
     *
     * @param pwdQuestionAnswer2 the value for js_sys_user.pwd_question_answer_2
     *
     * @mbg.generated
     */
    public void setPwdQuestionAnswer2(String pwdQuestionAnswer2) {
        this.pwdQuestionAnswer2 = pwdQuestionAnswer2 == null ? null : pwdQuestionAnswer2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.pwd_question_3
     *
     * @return the value of js_sys_user.pwd_question_3
     *
     * @mbg.generated
     */
    public String getPwdQuestion3() {
        return pwdQuestion3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.pwd_question_3
     *
     * @param pwdQuestion3 the value for js_sys_user.pwd_question_3
     *
     * @mbg.generated
     */
    public void setPwdQuestion3(String pwdQuestion3) {
        this.pwdQuestion3 = pwdQuestion3 == null ? null : pwdQuestion3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.pwd_question_answer_3
     *
     * @return the value of js_sys_user.pwd_question_answer_3
     *
     * @mbg.generated
     */
    public String getPwdQuestionAnswer3() {
        return pwdQuestionAnswer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.pwd_question_answer_3
     *
     * @param pwdQuestionAnswer3 the value for js_sys_user.pwd_question_answer_3
     *
     * @mbg.generated
     */
    public void setPwdQuestionAnswer3(String pwdQuestionAnswer3) {
        this.pwdQuestionAnswer3 = pwdQuestionAnswer3 == null ? null : pwdQuestionAnswer3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.pwd_quest_update_date
     *
     * @return the value of js_sys_user.pwd_quest_update_date
     *
     * @mbg.generated
     */
    public Date getPwdQuestUpdateDate() {
        return pwdQuestUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.pwd_quest_update_date
     *
     * @param pwdQuestUpdateDate the value for js_sys_user.pwd_quest_update_date
     *
     * @mbg.generated
     */
    public void setPwdQuestUpdateDate(Date pwdQuestUpdateDate) {
        this.pwdQuestUpdateDate = pwdQuestUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.last_login_ip
     *
     * @return the value of js_sys_user.last_login_ip
     *
     * @mbg.generated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.last_login_ip
     *
     * @param lastLoginIp the value for js_sys_user.last_login_ip
     *
     * @mbg.generated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.last_login_date
     *
     * @return the value of js_sys_user.last_login_date
     *
     * @mbg.generated
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.last_login_date
     *
     * @param lastLoginDate the value for js_sys_user.last_login_date
     *
     * @mbg.generated
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.freeze_date
     *
     * @return the value of js_sys_user.freeze_date
     *
     * @mbg.generated
     */
    public Date getFreezeDate() {
        return freezeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.freeze_date
     *
     * @param freezeDate the value for js_sys_user.freeze_date
     *
     * @mbg.generated
     */
    public void setFreezeDate(Date freezeDate) {
        this.freezeDate = freezeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.freeze_cause
     *
     * @return the value of js_sys_user.freeze_cause
     *
     * @mbg.generated
     */
    public String getFreezeCause() {
        return freezeCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.freeze_cause
     *
     * @param freezeCause the value for js_sys_user.freeze_cause
     *
     * @mbg.generated
     */
    public void setFreezeCause(String freezeCause) {
        this.freezeCause = freezeCause == null ? null : freezeCause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.user_weight
     *
     * @return the value of js_sys_user.user_weight
     *
     * @mbg.generated
     */
    public Integer getUserWeight() {
        return userWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.user_weight
     *
     * @param userWeight the value for js_sys_user.user_weight
     *
     * @mbg.generated
     */
    public void setUserWeight(Integer userWeight) {
        this.userWeight = userWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.status
     *
     * @return the value of js_sys_user.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.status
     *
     * @param status the value for js_sys_user.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.create_by
     *
     * @return the value of js_sys_user.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.create_by
     *
     * @param createBy the value for js_sys_user.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.create_date
     *
     * @return the value of js_sys_user.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.create_date
     *
     * @param createDate the value for js_sys_user.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.update_by
     *
     * @return the value of js_sys_user.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.update_by
     *
     * @param updateBy the value for js_sys_user.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.update_date
     *
     * @return the value of js_sys_user.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.update_date
     *
     * @param updateDate the value for js_sys_user.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.remarks
     *
     * @return the value of js_sys_user.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.remarks
     *
     * @param remarks the value for js_sys_user.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.corp_code
     *
     * @return the value of js_sys_user.corp_code
     *
     * @mbg.generated
     */
    public String getCorpCode() {
        return corpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.corp_code
     *
     * @param corpCode the value for js_sys_user.corp_code
     *
     * @mbg.generated
     */
    public void setCorpCode(String corpCode) {
        this.corpCode = corpCode == null ? null : corpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.corp_name
     *
     * @return the value of js_sys_user.corp_name
     *
     * @mbg.generated
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.corp_name
     *
     * @param corpName the value for js_sys_user.corp_name
     *
     * @mbg.generated
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName == null ? null : corpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_s1
     *
     * @return the value of js_sys_user.extend_s1
     *
     * @mbg.generated
     */
    public String getExtendS1() {
        return extendS1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_s1
     *
     * @param extendS1 the value for js_sys_user.extend_s1
     *
     * @mbg.generated
     */
    public void setExtendS1(String extendS1) {
        this.extendS1 = extendS1 == null ? null : extendS1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_s2
     *
     * @return the value of js_sys_user.extend_s2
     *
     * @mbg.generated
     */
    public String getExtendS2() {
        return extendS2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_s2
     *
     * @param extendS2 the value for js_sys_user.extend_s2
     *
     * @mbg.generated
     */
    public void setExtendS2(String extendS2) {
        this.extendS2 = extendS2 == null ? null : extendS2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_s3
     *
     * @return the value of js_sys_user.extend_s3
     *
     * @mbg.generated
     */
    public String getExtendS3() {
        return extendS3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_s3
     *
     * @param extendS3 the value for js_sys_user.extend_s3
     *
     * @mbg.generated
     */
    public void setExtendS3(String extendS3) {
        this.extendS3 = extendS3 == null ? null : extendS3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_s4
     *
     * @return the value of js_sys_user.extend_s4
     *
     * @mbg.generated
     */
    public String getExtendS4() {
        return extendS4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_s4
     *
     * @param extendS4 the value for js_sys_user.extend_s4
     *
     * @mbg.generated
     */
    public void setExtendS4(String extendS4) {
        this.extendS4 = extendS4 == null ? null : extendS4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_s5
     *
     * @return the value of js_sys_user.extend_s5
     *
     * @mbg.generated
     */
    public String getExtendS5() {
        return extendS5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_s5
     *
     * @param extendS5 the value for js_sys_user.extend_s5
     *
     * @mbg.generated
     */
    public void setExtendS5(String extendS5) {
        this.extendS5 = extendS5 == null ? null : extendS5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_s6
     *
     * @return the value of js_sys_user.extend_s6
     *
     * @mbg.generated
     */
    public String getExtendS6() {
        return extendS6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_s6
     *
     * @param extendS6 the value for js_sys_user.extend_s6
     *
     * @mbg.generated
     */
    public void setExtendS6(String extendS6) {
        this.extendS6 = extendS6 == null ? null : extendS6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_s7
     *
     * @return the value of js_sys_user.extend_s7
     *
     * @mbg.generated
     */
    public String getExtendS7() {
        return extendS7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_s7
     *
     * @param extendS7 the value for js_sys_user.extend_s7
     *
     * @mbg.generated
     */
    public void setExtendS7(String extendS7) {
        this.extendS7 = extendS7 == null ? null : extendS7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_s8
     *
     * @return the value of js_sys_user.extend_s8
     *
     * @mbg.generated
     */
    public String getExtendS8() {
        return extendS8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_s8
     *
     * @param extendS8 the value for js_sys_user.extend_s8
     *
     * @mbg.generated
     */
    public void setExtendS8(String extendS8) {
        this.extendS8 = extendS8 == null ? null : extendS8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_i1
     *
     * @return the value of js_sys_user.extend_i1
     *
     * @mbg.generated
     */
    public BigDecimal getExtendI1() {
        return extendI1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_i1
     *
     * @param extendI1 the value for js_sys_user.extend_i1
     *
     * @mbg.generated
     */
    public void setExtendI1(BigDecimal extendI1) {
        this.extendI1 = extendI1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_i2
     *
     * @return the value of js_sys_user.extend_i2
     *
     * @mbg.generated
     */
    public BigDecimal getExtendI2() {
        return extendI2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_i2
     *
     * @param extendI2 the value for js_sys_user.extend_i2
     *
     * @mbg.generated
     */
    public void setExtendI2(BigDecimal extendI2) {
        this.extendI2 = extendI2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_i3
     *
     * @return the value of js_sys_user.extend_i3
     *
     * @mbg.generated
     */
    public BigDecimal getExtendI3() {
        return extendI3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_i3
     *
     * @param extendI3 the value for js_sys_user.extend_i3
     *
     * @mbg.generated
     */
    public void setExtendI3(BigDecimal extendI3) {
        this.extendI3 = extendI3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_i4
     *
     * @return the value of js_sys_user.extend_i4
     *
     * @mbg.generated
     */
    public BigDecimal getExtendI4() {
        return extendI4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_i4
     *
     * @param extendI4 the value for js_sys_user.extend_i4
     *
     * @mbg.generated
     */
    public void setExtendI4(BigDecimal extendI4) {
        this.extendI4 = extendI4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_f1
     *
     * @return the value of js_sys_user.extend_f1
     *
     * @mbg.generated
     */
    public BigDecimal getExtendF1() {
        return extendF1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_f1
     *
     * @param extendF1 the value for js_sys_user.extend_f1
     *
     * @mbg.generated
     */
    public void setExtendF1(BigDecimal extendF1) {
        this.extendF1 = extendF1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_f2
     *
     * @return the value of js_sys_user.extend_f2
     *
     * @mbg.generated
     */
    public BigDecimal getExtendF2() {
        return extendF2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_f2
     *
     * @param extendF2 the value for js_sys_user.extend_f2
     *
     * @mbg.generated
     */
    public void setExtendF2(BigDecimal extendF2) {
        this.extendF2 = extendF2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_f3
     *
     * @return the value of js_sys_user.extend_f3
     *
     * @mbg.generated
     */
    public BigDecimal getExtendF3() {
        return extendF3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_f3
     *
     * @param extendF3 the value for js_sys_user.extend_f3
     *
     * @mbg.generated
     */
    public void setExtendF3(BigDecimal extendF3) {
        this.extendF3 = extendF3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_f4
     *
     * @return the value of js_sys_user.extend_f4
     *
     * @mbg.generated
     */
    public BigDecimal getExtendF4() {
        return extendF4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_f4
     *
     * @param extendF4 the value for js_sys_user.extend_f4
     *
     * @mbg.generated
     */
    public void setExtendF4(BigDecimal extendF4) {
        this.extendF4 = extendF4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_d1
     *
     * @return the value of js_sys_user.extend_d1
     *
     * @mbg.generated
     */
    public Date getExtendD1() {
        return extendD1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_d1
     *
     * @param extendD1 the value for js_sys_user.extend_d1
     *
     * @mbg.generated
     */
    public void setExtendD1(Date extendD1) {
        this.extendD1 = extendD1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_d2
     *
     * @return the value of js_sys_user.extend_d2
     *
     * @mbg.generated
     */
    public Date getExtendD2() {
        return extendD2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_d2
     *
     * @param extendD2 the value for js_sys_user.extend_d2
     *
     * @mbg.generated
     */
    public void setExtendD2(Date extendD2) {
        this.extendD2 = extendD2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_d3
     *
     * @return the value of js_sys_user.extend_d3
     *
     * @mbg.generated
     */
    public Date getExtendD3() {
        return extendD3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_d3
     *
     * @param extendD3 the value for js_sys_user.extend_d3
     *
     * @mbg.generated
     */
    public void setExtendD3(Date extendD3) {
        this.extendD3 = extendD3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_sys_user.extend_d4
     *
     * @return the value of js_sys_user.extend_d4
     *
     * @mbg.generated
     */
    public Date getExtendD4() {
        return extendD4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_sys_user.extend_d4
     *
     * @param extendD4 the value for js_sys_user.extend_d4
     *
     * @mbg.generated
     */
    public void setExtendD4(Date extendD4) {
        this.extendD4 = extendD4;
    }
}