package com.init.mini.web.mapper;

import com.init.mini.web.entity.JsSysUser;

public interface JsSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_sys_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_sys_user
     *
     * @mbg.generated
     */
    int insert(JsSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_sys_user
     *
     * @mbg.generated
     */
    int insertSelective(JsSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_sys_user
     *
     * @mbg.generated
     */
    JsSysUser selectByPrimaryKey(String userCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JsSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JsSysUser record);
}